Repository 42-AI/Elegant-Elegans, pull requests merged in 2022-09, with the labels that each got.

#58 57 docssetup setup wf ntp under windows
  Setup.md
Labels: documentation

#56 add conda environment requirements in yml file for windows setup
  env_wf_ntp.yml
Labels: feature, env

#62 doc + update (Readme + Setup): traduction de setup.md
  README.md
  Setup.md
Labels: documentation, enhancement

#63 61 update documentation minor fix on readme
  Setup.md
Labels: documentation, enhancement

#64 51 bug undefined variable in exception message in converterparserpy
  converter/convert.py
  converter/parser.py
Labels: bug, fixme

#66 Activity index documentation
  docs/WF_NTP-activity_index.md
Labels: documentation
